import type { NexoraBotTeaching } from "./nexoraBotTeachingRegistry";

const ALL_SYMBOLS = ["BTC/USD", "ETH/USD", "SOL/USD", "XAUUSD"];
const ALL_STRATEGIES = ["momentum_breakout", "volatility_squeeze", "trend_follow", "mean_reversion"];

export const NEXORA_ADVANCED_PROFESSOR_TEACHINGS: NexoraBotTeaching[] = [
  {
    id: "professor_expectancy_math",
    title: "Expectancy Mathematics",
    category: "profitability",
    enabled: true,
    priority: 120,
    lesson: "A bot must judge a setup by expectancy, not excitement. Expected value equals win probability times average win minus loss probability times average loss.",
    rule: "Do not promote any setup unless expectancy is positive over enough trades.",
    tradeImpact: "promotion_control",
    appliesToStrategies: ALL_STRATEGIES,
    appliesToSymbols: ALL_SYMBOLS,
  },
  {
    id: "professor_asymmetric_reward",
    title: "Asymmetric Reward Design",
    category: "risk",
    enabled: true,
    priority: 119,
    lesson: "The bot should prefer setups where potential reward is meaningfully larger than risk.",
    rule: "Reject setups where target is too small compared with stop distance.",
    tradeImpact: "reject_if_failed",
    appliesToStrategies: ALL_STRATEGIES,
    appliesToSymbols: ALL_SYMBOLS,
  },
  {
    id: "professor_loss_size_discipline",
    title: "Loss Size Discipline",
    category: "drawdown",
    enabled: true,
    priority: 119,
    lesson: "Large losses destroy learning. Small controlled losses are acceptable; oversized losses are not.",
    rule: "Reduce risk after large losses and block setups with repeated outsized losses.",
    tradeImpact: "risk_reduce",
    appliesToStrategies: ALL_STRATEGIES,
    appliesToSymbols: ALL_SYMBOLS,
  },
  {
    id: "professor_sample_size_truth",
    title: "Sample Size Truth",
    category: "validation",
    enabled: true,
    priority: 118,
    lesson: "A setup with 5 wins is not proven. A setup needs enough samples across different conditions before trust increases.",
    rule: "Treat low-sample setups as testing only, no matter how good they look.",
    tradeImpact: "promotion_control",
    appliesToStrategies: ALL_STRATEGIES,
    appliesToSymbols: ALL_SYMBOLS,
  },
  {
    id: "professor_false_breakout_awareness",
    title: "False Breakout Awareness",
    category: "trade_filtering",
    enabled: true,
    priority: 118,
    lesson: "Breakouts fail often when volume, retest, liquidity and regime do not confirm.",
    rule: "Momentum breakout requires confirmation from volume, structure and regime.",
    tradeImpact: "reject_if_failed",
    appliesToStrategies: ["momentum_breakout", "volatility_squeeze"],
    appliesToSymbols: ALL_SYMBOLS,
  },
  {
    id: "professor_liquidity_grab_awareness",
    title: "Liquidity Grab Awareness",
    category: "trade_filtering",
    enabled: true,
    priority: 117,
    lesson: "Markets often sweep highs or lows to trigger stops before reversing.",
    rule: "Avoid entries immediately after obvious stop sweeps unless reversal structure confirms.",
    tradeImpact: "risk_reduce",
    appliesToStrategies: ALL_STRATEGIES,
    appliesToSymbols: ALL_SYMBOLS,
  },
  {
    id: "professor_regime_strategy_matching",
    title: "Regime Strategy Matching",
    category: "regime",
    enabled: true,
    priority: 117,
    lesson: "Trend systems belong in trend regimes. Mean-reversion systems belong in range regimes.",
    rule: "Reject strategy if market regime does not match the strategy type.",
    tradeImpact: "reject_if_failed",
    appliesToStrategies: ALL_STRATEGIES,
    appliesToSymbols: ALL_SYMBOLS,
  },
  {
    id: "professor_crypto_correlation_risk",
    title: "Crypto Correlation Risk",
    category: "symbol_behavior",
    enabled: true,
    priority: 116,
    lesson: "BTC, ETH and SOL are often correlated during broad crypto risk events.",
    rule: "Do not stack correlated crypto exposure during weak learning or risk-off conditions.",
    tradeImpact: "risk_reduce",
    appliesToStrategies: ALL_STRATEGIES,
    appliesToSymbols: ["BTC/USD", "ETH/USD", "SOL/USD"],
  },
  {
    id: "professor_sol_high_beta_caution",
    title: "SOL High-Beta Caution",
    category: "symbol_behavior",
    enabled: true,
    priority: 116,
    lesson: "SOL can move faster and reverse harder than BTC or ETH.",
    rule: "Keep SOL micro-sized or blocked until its own profit factor is positive.",
    tradeImpact: "size_reduce",
    appliesToStrategies: ALL_STRATEGIES,
    appliesToSymbols: ["SOL/USD"],
  },
  {
    id: "professor_btc_market_leader",
    title: "BTC Market Leader",
    category: "symbol_behavior",
    enabled: true,
    priority: 115,
    lesson: "BTC often leads crypto direction and controls broad crypto sentiment.",
    rule: "Reduce ETH/SOL long confidence when BTC market structure is weak.",
    tradeImpact: "risk_reduce",
    appliesToStrategies: ALL_STRATEGIES,
    appliesToSymbols: ["ETH/USD", "SOL/USD"],
  },
  {
    id: "professor_gold_macro_separation",
    title: "Gold Macro Separation",
    category: "symbol_behavior",
    enabled: true,
    priority: 115,
    lesson: "XAUUSD should not be treated like crypto. Gold reacts to macro, dollar, rates and risk-off flows.",
    rule: "Score XAUUSD with separate regime assumptions from crypto.",
    tradeImpact: "risk_reduce",
    appliesToStrategies: ALL_STRATEGIES,
    appliesToSymbols: ["XAUUSD"],
  },
  {
    id: "professor_slippage_kills_edges",
    title: "Slippage Kills Edges",
    category: "risk",
    enabled: true,
    priority: 115,
    lesson: "A setup that looks profitable before slippage can become losing after execution costs.",
    rule: "Reject or reduce trades when expected edge is smaller than spread/slippage cost.",
    tradeImpact: "reject_if_failed",
    appliesToStrategies: ALL_STRATEGIES,
    appliesToSymbols: ALL_SYMBOLS,
  },
  {
    id: "professor_time_of_day_effect",
    title: "Time-of-Day Effect",
    category: "market_data",
    enabled: true,
    priority: 112,
    lesson: "Liquidity and volatility change by session. Some strategies perform better at specific times.",
    rule: "Track session/time metadata and use it in promotion decisions.",
    tradeImpact: "promotion_control",
    appliesToStrategies: ALL_STRATEGIES,
    appliesToSymbols: ALL_SYMBOLS,
  },
  {
    id: "professor_no_trade_is_position",
    title: "No Trade Is a Position",
    category: "trade_filtering",
    enabled: true,
    priority: 116,
    lesson: "Waiting is an active decision. A bot that avoids bad trades is improving.",
    rule: "When edge is unclear, monitor only instead of forcing a paper trade.",
    tradeImpact: "monitor_only",
    appliesToStrategies: ALL_STRATEGIES,
    appliesToSymbols: ALL_SYMBOLS,
  },
  {
    id: "professor_losing_streak_cooldown",
    title: "Losing Streak Cooldown",
    category: "drawdown",
    enabled: true,
    priority: 116,
    lesson: "After consecutive losses, the bot should slow down and lower size.",
    rule: "Reduce risk or pause after repeated losses in a short window.",
    tradeImpact: "monitor_only",
    appliesToStrategies: ALL_STRATEGIES,
    appliesToSymbols: ALL_SYMBOLS,
  },
  {
    id: "professor_dynamic_confidence_floor",
    title: "Dynamic Confidence Floor",
    category: "risk",
    enabled: true,
    priority: 113,
    lesson: "Confidence requirements should rise when performance is weak and loosen only when proven.",
    rule: "Increase required confidence when learning score and profit factor are poor.",
    tradeImpact: "reject_if_failed",
    appliesToStrategies: ALL_STRATEGIES,
    appliesToSymbols: ALL_SYMBOLS,
  },
  {
    id: "professor_indicator_disagreement",
    title: "Indicator Disagreement Handling",
    category: "signal_agreement",
    enabled: true,
    priority: 114,
    lesson: "Mixed signals are a warning. The bot should not pretend uncertainty is confidence.",
    rule: "Reject trades when trend, structure and liquidity disagree.",
    tradeImpact: "reject_if_failed",
    appliesToStrategies: ALL_STRATEGIES,
    appliesToSymbols: ALL_SYMBOLS,
  },
  {
    id: "professor_overfitting_awareness",
    title: "Overfitting Awareness",
    category: "validation",
    enabled: true,
    priority: 114,
    lesson: "A setup that only works on one small sample may be curve-fitted.",
    rule: "Require walk-forward validation before promotion.",
    tradeImpact: "promotion_control",
    appliesToStrategies: ALL_STRATEGIES,
    appliesToSymbols: ALL_SYMBOLS,
  },
  {
    id: "professor_outlier_handling",
    title: "Outlier Handling",
    category: "profitability",
    enabled: true,
    priority: 112,
    lesson: "One lucky winner or one extreme loser should not define the whole system.",
    rule: "Track median P&L as well as average P&L before promotion.",
    tradeImpact: "promotion_control",
    appliesToStrategies: ALL_STRATEGIES,
    appliesToSymbols: ALL_SYMBOLS,
  },
  {
    id: "professor_max_adverse_excursion",
    title: "Maximum Adverse Excursion",
    category: "risk",
    enabled: true,
    priority: 113,
    lesson: "Study how far trades go against the bot before winning or losing.",
    rule: "Tighten entries or stops when adverse excursion is consistently too large.",
    tradeImpact: "risk_reduce",
    appliesToStrategies: ALL_STRATEGIES,
    appliesToSymbols: ALL_SYMBOLS,
  },
  {
    id: "professor_max_favorable_excursion",
    title: "Maximum Favorable Excursion",
    category: "profitability",
    enabled: true,
    priority: 112,
    lesson: "Study how much profit trades show before reversing.",
    rule: "Improve exits and trailing logic if winners often give back profit.",
    tradeImpact: "promotion_control",
    appliesToStrategies: ALL_STRATEGIES,
    appliesToSymbols: ALL_SYMBOLS,
  },
  {
    id: "professor_stop_target_symmetry",
    title: "Stop/Target Symmetry",
    category: "risk",
    enabled: true,
    priority: 112,
    lesson: "Stops and targets must match the behaviour of the symbol and strategy.",
    rule: "Do not use one fixed stop/target style for all symbols.",
    tradeImpact: "risk_reduce",
    appliesToStrategies: ALL_STRATEGIES,
    appliesToSymbols: ALL_SYMBOLS,
  },
  {
    id: "professor_trailing_stop_education",
    title: "Trailing Stop Education",
    category: "risk",
    enabled: true,
    priority: 111,
    lesson: "Trailing stops can protect winners, but too-tight trailing stops can kill good trends.",
    rule: "Use trailing stops only after price moves enough in favour.",
    tradeImpact: "risk_reduce",
    appliesToStrategies: ["momentum_breakout", "trend_follow"],
    appliesToSymbols: ALL_SYMBOLS,
  },
  {
    id: "professor_partial_profit_logic",
    title: "Partial Profit Logic",
    category: "profitability",
    enabled: true,
    priority: 110,
    lesson: "Taking partial profit can reduce emotional and statistical pressure on the remaining trade.",
    rule: "Consider partial exits only after enough favourable movement.",
    tradeImpact: "promotion_control",
    appliesToStrategies: ["momentum_breakout", "trend_follow", "volatility_squeeze"],
    appliesToSymbols: ALL_SYMBOLS,
  },
  {
    id: "professor_reentry_discipline",
    title: "Re-Entry Discipline",
    category: "trade_filtering",
    enabled: true,
    priority: 110,
    lesson: "After a stopped trade, immediate re-entry is dangerous unless the setup resets.",
    rule: "Cooldown same symbol/strategy after stop-hit exits.",
    tradeImpact: "monitor_only",
    appliesToStrategies: ALL_STRATEGIES,
    appliesToSymbols: ALL_SYMBOLS,
  },
  {
    id: "professor_avoid_mid_range_entries",
    title: "Avoid Mid-Range Entries",
    category: "trade_filtering",
    enabled: true,
    priority: 111,
    lesson: "Entries in the middle of a range often have poor reward/risk.",
    rule: "Prefer entries near structure, confirmed breakout, or confirmed reversion zones.",
    tradeImpact: "reject_if_failed",
    appliesToStrategies: ALL_STRATEGIES,
    appliesToSymbols: ALL_SYMBOLS,
  },
  {
    id: "professor_support_resistance_respect",
    title: "Support and Resistance Respect",
    category: "trade_filtering",
    enabled: true,
    priority: 111,
    lesson: "Do not buy directly into resistance or short directly into support.",
    rule: "Reject trades when nearby structure blocks reward.",
    tradeImpact: "reject_if_failed",
    appliesToStrategies: ALL_STRATEGIES,
    appliesToSymbols: ALL_SYMBOLS,
  },
  {
    id: "professor_market_structure_first",
    title: "Market Structure First",
    category: "regime",
    enabled: true,
    priority: 113,
    lesson: "Structure matters before indicators. Indicators should confirm structure, not replace it.",
    rule: "Prefer trades aligned with break of structure, retest, or clear range edges.",
    tradeImpact: "approve_boost",
    appliesToStrategies: ALL_STRATEGIES,
    appliesToSymbols: ALL_SYMBOLS,
  },
  {
    id: "professor_volume_participation",
    title: "Volume Participation",
    category: "trade_filtering",
    enabled: true,
    priority: 112,
    lesson: "Breakouts without participation are more likely to fail.",
    rule: "Require volume confirmation for breakout and squeeze trades.",
    tradeImpact: "reject_if_failed",
    appliesToStrategies: ["momentum_breakout", "volatility_squeeze"],
    appliesToSymbols: ["BTC/USD", "ETH/USD", "SOL/USD"],
  },
  {
    id: "professor_volatility_expansion_confirmation",
    title: "Volatility Expansion Confirmation",
    category: "volatility",
    enabled: true,
    priority: 112,
    lesson: "A squeeze should not be traded just because volatility is low. It needs expansion confirmation.",
    rule: "Block squeeze trades until expansion confirms direction.",
    tradeImpact: "reject_if_failed",
    appliesToStrategies: ["volatility_squeeze"],
    appliesToSymbols: ALL_SYMBOLS,
  },
  {
    id: "professor_mean_reversion_trend_danger",
    title: "Mean Reversion Trend Danger",
    category: "regime",
    enabled: true,
    priority: 111,
    lesson: "Mean reversion can get crushed in strong trends.",
    rule: "Reject mean reversion against strong trend unless structure confirms exhaustion.",
    tradeImpact: "reject_if_failed",
    appliesToStrategies: ["mean_reversion"],
    appliesToSymbols: ALL_SYMBOLS,
  },
  {
    id: "professor_breakout_range_danger",
    title: "Breakout Range Danger",
    category: "regime",
    enabled: true,
    priority: 111,
    lesson: "Breakout systems perform poorly when the market is mean-reverting inside a range.",
    rule: "Require range break and retest confirmation for breakout trades in range conditions.",
    tradeImpact: "reject_if_failed",
    appliesToStrategies: ["momentum_breakout", "volatility_squeeze"],
    appliesToSymbols: ALL_SYMBOLS,
  },
  {
    id: "professor_data_quality_before_action",
    title: "Data Quality Before Action",
    category: "market_data",
    enabled: true,
    priority: 113,
    lesson: "Bad data creates bad trades.",
    rule: "Reduce confidence or monitor-only if candles, volume, spread, or outcome data are stale.",
    tradeImpact: "monitor_only",
    appliesToStrategies: ALL_STRATEGIES,
    appliesToSymbols: ALL_SYMBOLS,
  },
  {
    id: "professor_paper_to_live_wall",
    title: "Paper-to-Live Wall",
    category: "risk",
    enabled: true,
    priority: 120,
    lesson: "Paper success does not automatically mean live trading is safe.",
    rule: "Never enable live trading without separate live-readiness approval, tiny size, and compliance review.",
    tradeImpact: "reject_if_failed",
    appliesToStrategies: ALL_STRATEGIES,
    appliesToSymbols: ALL_SYMBOLS,
  },
  {
    id: "professor_capital_preservation",
    title: "Capital Preservation First",
    category: "risk",
    enabled: true,
    priority: 120,
    lesson: "The first goal is survival. A bot that survives can keep learning.",
    rule: "When uncertainty is high, protect capital and monitor only.",
    tradeImpact: "monitor_only",
    appliesToStrategies: ALL_STRATEGIES,
    appliesToSymbols: ALL_SYMBOLS,
  }
];
