import type { NewsItem } from "./types";

export function buildNews(): NewsItem[] {
  const now = Date.now();
  return [
    {
      id: "news-001",
      timestamp: new Date(now - 1800000).toISOString(),
      headline: "Federal Reserve signals potential rate pause in upcoming meeting",
      source: "Reuters",
      sentiment: "bullish",
      relevance: 0.95,
      markets: ["BTC/USD", "ETH/USD", "XAUUSD", "SOL/USD"],
      summary: "Fed Chair indicated that economic data supports maintaining current rates, reducing pressure on risk assets. Treasury yields dropped 8bps on the news. Historically, rate pauses have been bullish for both crypto and gold, with BTC averaging +12% in the 30 days following a pause signal.",
      impact: "high",
      sourceUrl: null,
      linkedDecisionIds: ["td-1001", "td-1002"],
    },
    {
      id: "news-002",
      timestamp: new Date(now - 3600000).toISOString(),
      headline: "Bitcoin ETF inflows reach $780M in single day — highest since March",
      source: "Bloomberg",
      sentiment: "bullish",
      relevance: 0.92,
      markets: ["BTC/USD"],
      summary: "Spot Bitcoin ETFs recorded massive inflows led by BlackRock iShares Bitcoin Trust ($412M) and Fidelity Wise Origin ($198M). This represents the strongest single-day inflow since mid-March and suggests institutional accumulation is accelerating. Grayscale saw net zero outflows for the first time in 2024.",
      impact: "high",
      sourceUrl: null,
      linkedDecisionIds: ["td-1001", "td-1005"],
    },
    {
      id: "news-003",
      timestamp: new Date(now - 5400000).toISOString(),
      headline: "Central banks purchased 290 tonnes of gold in Q1 — China and India leading",
      source: "World Gold Council",
      sentiment: "bullish",
      relevance: 0.88,
      markets: ["XAUUSD"],
      summary: "Central bank gold purchases continue at an elevated pace with China adding 45 tonnes and India adding 32 tonnes to reserves. The trend of de-dollarisation and reserve diversification supports structural demand for gold above current levels. Gold-backed ETF holdings have also increased for 4 consecutive months.",
      impact: "high",
      sourceUrl: null,
      linkedDecisionIds: ["td-1002"],
    },
    {
      id: "news-004",
      timestamp: new Date(now - 7200000).toISOString(),
      headline: "Ethereum Pectra upgrade successfully deployed on testnet",
      source: "CoinDesk",
      sentiment: "neutral",
      relevance: 0.75,
      markets: ["ETH/USD"],
      summary: "The Pectra upgrade combining Prague and Electra changes went live on the Holesky testnet without issues. Key improvements include account abstraction (EIP-7702), increased blob capacity, and validator staking cap increases. Mainnet deployment expected in Q2. Market reaction was muted as the upgrade was largely priced in.",
      impact: "medium",
      sourceUrl: null,
      linkedDecisionIds: ["td-1003"],
    },
    {
      id: "news-005",
      timestamp: new Date(now - 10800000).toISOString(),
      headline: "US Dollar Index (DXY) breaks below 104 for first time in 3 months",
      source: "Financial Times",
      sentiment: "bullish",
      relevance: 0.90,
      markets: ["BTC/USD", "XAUUSD", "ETH/USD"],
      summary: "The US Dollar weakened against major currencies as economic data showed cooling inflation. DXY fell to 103.8, its lowest level since January. Dollar weakness historically correlates strongly with rallies in both gold and Bitcoin. The inverse correlation between DXY and BTC has been -0.78 over the past 90 days.",
      impact: "high",
      sourceUrl: null,
      linkedDecisionIds: ["td-1001", "td-1002"],
    },
    {
      id: "news-006",
      timestamp: new Date(now - 14400000).toISOString(),
      headline: "Solana DEX volume exceeds Ethereum for 5th consecutive week",
      source: "The Block",
      sentiment: "bullish",
      relevance: 0.82,
      markets: ["SOL/USD"],
      summary: "Solana decentralised exchange volume reached $18.2B this week versus Ethereum's $14.8B, marking the 5th straight week of outperformance. Jupiter aggregator processed $8.4B alone. Network revenue from fees hit an all-time high, and active addresses surpassed 2.4M daily. The SOL/ETH ratio is at its highest level ever.",
      impact: "medium",
      sourceUrl: null,
      linkedDecisionIds: ["td-1004"],
    },
    {
      id: "news-007",
      timestamp: new Date(now - 18000000).toISOString(),
      headline: "Bitcoin mining difficulty hits new all-time high — hash rate at 850 EH/s",
      source: "Glassnode",
      sentiment: "bullish",
      relevance: 0.78,
      markets: ["BTC/USD"],
      summary: "Bitcoin mining difficulty increased 3.2% to a new record, reflecting hash rate reaching 850 EH/s. Higher difficulty means greater security and miner commitment. Post-halving economics are stabilising as transaction fee revenue supplements reduced block rewards. Miner reserves remain steady, indicating no forced selling pressure.",
      impact: "low",
      sourceUrl: null,
      linkedDecisionIds: [],
    },
    {
      id: "news-008",
      timestamp: new Date(now - 21600000).toISOString(),
      headline: "Geopolitical tensions in Middle East escalate — safe haven flows increase",
      source: "Reuters",
      sentiment: "bearish",
      relevance: 0.85,
      markets: ["XAUUSD", "BTC/USD"],
      summary: "Rising tensions have triggered safe-haven inflows into gold and US Treasuries. Gold gained $18 on the news. Bitcoin's response was mixed — initially selling off 2% before recovering as some traders repositioned it as 'digital gold'. Risk appetite in broader markets declined with VIX rising to 18.2.",
      impact: "medium",
      sourceUrl: null,
      linkedDecisionIds: ["td-1002"],
    },
    {
      id: "news-009",
      timestamp: new Date(now - 25200000).toISOString(),
      headline: "Whale accumulation: Addresses holding 1K+ BTC add 28,000 BTC in past week",
      source: "Santiment",
      sentiment: "bullish",
      relevance: 0.87,
      markets: ["BTC/USD"],
      summary: "On-chain data shows large holders (1,000+ BTC wallets) accumulated 28,000 BTC ($2.3B) over the past 7 days, the largest weekly accumulation since November 2023. Exchange balances dropped to a 5-year low of 2.26M BTC. The supply squeeze narrative is strengthening as available supply on exchanges decreases while ETF inflows increase.",
      impact: "high",
      sourceUrl: null,
      linkedDecisionIds: ["td-1001"],
    },
    {
      id: "news-010",
      timestamp: new Date(now - 28800000).toISOString(),
      headline: "Japan's BOJ maintains negative rate stance — Yen weakens to 155/USD",
      source: "Nikkei Asia",
      sentiment: "neutral",
      relevance: 0.72,
      markets: ["BTC/USD", "XAUUSD"],
      summary: "Bank of Japan held rates steady, disappointing hawks who expected tightening. The Yen weakened past 155 to the dollar. This supports the broader 'currency debasement' narrative that benefits hard assets like Bitcoin and gold. Japanese institutional investors have been increasing exposure to dollar-denominated assets including crypto.",
      impact: "medium",
      sourceUrl: null,
      linkedDecisionIds: [],
    },
    {
      id: "news-011",
      timestamp: new Date(now - 32400000).toISOString(),
      headline: "Tether treasury prints $1B USDT on Ethereum — largest single mint in 6 months",
      source: "Whale Alert",
      sentiment: "bullish",
      relevance: 0.80,
      markets: ["BTC/USD", "ETH/USD", "SOL/USD"],
      summary: "Tether minted $1B USDT in a single transaction, typically a leading indicator of incoming buy pressure. Historically, large USDT mints have preceded BTC rallies within 48-72 hours as the new stablecoins are deployed into the market. Total USDT supply now exceeds $145B.",
      impact: "medium",
      sourceUrl: null,
      linkedDecisionIds: [],
    },
    {
      id: "news-012",
      timestamp: new Date(now - 36000000).toISOString(),
      headline: "SEC Commissioner signals openness to broader crypto regulation framework",
      source: "WSJ",
      sentiment: "bullish",
      relevance: 0.83,
      markets: ["ETH/USD", "SOL/USD"],
      summary: "SEC Commissioner Hester Peirce outlined a potential regulatory framework that could provide clarity for altcoins and DeFi protocols. The proposal includes safe harbour provisions for token projects and clearer guidelines on what constitutes a security. Market participants view this as a positive shift from enforcement-first approach.",
      impact: "medium",
      sourceUrl: null,
      linkedDecisionIds: [],
    },
  ];
}
