import type { StrategyProfile } from "./types";

export function buildStrategies(): StrategyProfile[] {
  return [
    {
      name: "momentum_breakout",
      description: "Captures strong directional moves when price breaks through established support/resistance with volume confirmation. Targets the initial impulse move after the breakout.",
      edge: "High-probability entries when volume confirms the breakout direction, catching the fastest part of the move before mean-reversion forces take over.",
      idealRegime: "trending",
      winRate: 62,
      avgRR: 2.1,
      avgHoldTime: "4-12 hours",
      riskPerTrade: "1.5% of paper capital",
      entryRules: [
        "Price breaks above/below key horizontal level with at least 1.5x average volume",
        "RSI(14) confirms direction (>55 for long breakout, <45 for short)",
        "MACD histogram expanding in breakout direction",
        "ADX > 25 confirming trend strength",
        "No major resistance/support within 1 ATR of entry in trade direction",
      ],
      exitRules: [
        "Take profit at 2:1 reward-to-risk ratio",
        "Trail stop to breakeven after 1R move",
        "Close 50% at 1.5R, trail remainder with 2-ATR stop",
        "Exit on volume exhaustion (volume drops below average on continuation)",
      ],
      invalidationRules: [
        "Price closes back inside the range within 2 candles",
        "Volume dries up immediately after breakout (false breakout signal)",
        "Opposing macro news event within 30 minutes of entry",
      ],
      strengths: ["High R:R ratio", "Clear entry/exit rules", "Works well in trending markets", "Quick to identify false breakouts"],
      weaknesses: ["Whipsaws in ranging markets", "Slippage on volatile breakouts", "Requires real-time volume data", "Lower win rate than mean reversion"],
      version: "1.0.0",
      isActive: true,
      powersDecisions: true,
      ruleSource: "server/services/trading/strategies.ts",
      lastUsedAt: null,
    },
    {
      name: "mean_reversion",
      description: "Fades extreme moves by entering counter-trend when price reaches statistical extremes (Bollinger Band outer edges, RSI overbought/oversold) with regime confirmation that conditions favor snapback.",
      edge: "Statistically, price reverts to the mean 60-70% of the time in range-bound regimes. Tight stops limit downside when trend continuation invalidates the setup.",
      idealRegime: "ranging",
      winRate: 68,
      avgRR: 1.3,
      avgHoldTime: "1-4 hours",
      riskPerTrade: "1% of paper capital",
      entryRules: [
        "Price touches or exceeds 2-standard-deviation Bollinger Band",
        "RSI(14) > 75 (short) or < 25 (long)",
        "ADX < 20 confirming range-bound conditions",
        "Stochastic RSI showing divergence from price",
        "MFI confirms exhaustion (>80 for short, <20 for long)",
        "No earnings or major macro event within 4 hours",
      ],
      exitRules: [
        "Target: 20-period moving average (the 'mean')",
        "Stop: 0.5 ATR beyond the extreme",
        "Time stop: Exit if no reversion within 6 hours",
        "Close if ADX starts rising above 25 (regime shift to trend)",
      ],
      invalidationRules: [
        "ADX crosses above 30 (strong trend forming, not a reversion setup)",
        "Price makes new extreme on higher volume (continuation, not exhaustion)",
        "Funding rate extreme and rising (crypto-specific leverage indicator)",
      ],
      strengths: ["High win rate", "Quick trades", "Works in choppy markets", "Low drawdown per trade"],
      weaknesses: ["Small R:R means a few losses wipe many wins", "Fails catastrophically in strong trends", "Requires accurate regime detection"],
      version: "1.0.0",
      isActive: true,
      powersDecisions: true,
      ruleSource: "server/services/trading/strategies.ts",
      lastUsedAt: null,
    },
    {
      name: "trend_follow",
      description: "Rides established trends by entering on pullbacks to dynamic support/resistance (EMAs, VWAP). Holds position as long as the trend structure remains intact, using trailing stops to capture large moves.",
      edge: "Trends persist longer than most market participants expect. Pullback entries provide favourable risk:reward by entering closer to the trend's support structure.",
      idealRegime: "trending",
      winRate: 55,
      avgRR: 3.2,
      avgHoldTime: "12-48 hours",
      riskPerTrade: "1.5% of paper capital",
      entryRules: [
        "Price above EMA(20) and EMA(50), both sloping in trend direction",
        "Pullback touches EMA(20) or VWAP and bounces",
        "ADX > 25 and DI+ > DI- (uptrend) or DI- > DI+ (downtrend)",
        "Volume decreases during pullback, increases on bounce (healthy trend)",
        "Higher timeframe (4H/daily) confirms same trend direction",
      ],
      exitRules: [
        "Initial stop: Below EMA(50) or swing low",
        "Trail stop using 3-ATR from price or EMA(20)",
        "Close 33% at 2R, 33% at 3R, trail final 33%",
        "Exit on EMA(20) crossing below EMA(50)",
      ],
      invalidationRules: [
        "Price closes below EMA(50) on volume",
        "ADX drops below 20 (trend losing strength)",
        "Series of lower highs in uptrend or higher lows in downtrend",
      ],
      strengths: ["Large winners capture big moves", "Rides trends for maximum profit", "Clear trend-structure-based stops", "Scales well across timeframes"],
      weaknesses: ["Low win rate requires discipline", "Slow to exit — gives back profit on reversals", "Doesn't work in choppy/ranging markets"],
      version: "1.0.0",
      isActive: true,
      powersDecisions: true,
      ruleSource: "server/services/trading/strategies.ts",
      lastUsedAt: null,
    },
    {
      name: "volatility_squeeze",
      description: "Identifies periods of unusually low volatility (Bollinger Band width contraction, ATR compression) and positions for the explosive move that typically follows. Direction determined by order flow and momentum indicators.",
      edge: "Volatility is mean-reverting: periods of compression are reliably followed by expansion. The squeeze pattern is one of the most consistent setups across all liquid markets.",
      idealRegime: "low_volatility",
      winRate: 58,
      avgRR: 2.5,
      avgHoldTime: "2-8 hours",
      riskPerTrade: "1% of paper capital",
      entryRules: [
        "Bollinger Band width falls to lowest level in 20 periods",
        "Keltner Channels inside Bollinger Bands (classic squeeze signal)",
        "ATR(14) at or near 20-period low",
        "Wait for first candle to close outside the squeeze range",
        "Enter in direction of the breakout with momentum confirmation (MACD cross)",
      ],
      exitRules: [
        "Target: 2.5x the width of the squeeze range",
        "Stop: Opposite side of the squeeze range",
        "Trail using 2-ATR once move exceeds 1.5R",
        "Exit if momentum indicator (MACD histogram) starts declining within 3 candles",
      ],
      invalidationRules: [
        "Price re-enters squeeze range and closes inside it",
        "Volume doesn't increase on breakout (low-conviction move)",
        "Squeeze lasts more than 40 periods without resolution (pattern degradation)",
      ],
      strengths: ["Excellent R:R from tight stops", "Repeatable pattern", "Works across all liquid markets", "Clear visual setup"],
      weaknesses: ["False breakouts common", "Requires patience waiting for squeeze", "Timing of entry is critical"],
      version: "1.0.0",
      isActive: true,
      powersDecisions: true,
      ruleSource: "server/services/trading/strategies.ts",
      lastUsedAt: null,
    },
    {
      name: "regime_shift",
      description: "Detects transitions between market regimes (trending to ranging, low vol to high vol) and positions early in the new regime. Uses a combination of volatility metrics, trend strength, and structural analysis.",
      edge: "Most strategies fail during regime transitions because they're calibrated for the previous regime. This strategy profits from the transition itself — the most dislocating and profitable phase.",
      idealRegime: "transition",
      winRate: 48,
      avgRR: 4.0,
      avgHoldTime: "24-72 hours",
      riskPerTrade: "0.75% of paper capital",
      entryRules: [
        "ADX crosses above 25 from below (trend emerging from range)",
        "ATR expanding 50%+ from 20-period average",
        "EMA(20) crosses EMA(50) (golden/death cross forming)",
        "Volume surge: 2x average for 3+ consecutive periods",
        "Correlation with correlated assets confirms regime change (e.g., BTC leads alts)",
        "Macro catalyst identified (rate decision, major news, regulatory change)",
      ],
      exitRules: [
        "Hold until new regime is established (ADX sustained above 30 for trend)",
        "Take partial profits at 3R and 5R",
        "Exit if regime change fails (ADX drops back below 20 within 48 hours)",
        "Exit on counter-regime signals appearing",
      ],
      invalidationRules: [
        "ADX reversal back below 20 within 24 hours",
        "Volume returns to average levels (regime change not confirmed by participation)",
        "Price fails to make new high/low in expected direction within 48 hours",
      ],
      strengths: ["Massive R:R potential", "Catches the biggest moves", "First-mover advantage in new regime", "Works across all asset classes"],
      weaknesses: ["Lowest win rate of all strategies", "Requires patience and conviction", "False regime shifts are costly", "Hardest strategy to execute psychologically"],
      version: "1.0.0",
      isActive: true,
      powersDecisions: true,
      ruleSource: "server/services/trading/strategies.ts",
      lastUsedAt: null,
    },
    {
      name: "order_flow_scalp",
      description: "Micro-scalping strategy using order book imbalance, trade flow analysis, and CVD (Cumulative Volume Delta) to identify short-term directional moves. Targets 0.3-0.8% moves on leveraged positions.",
      edge: "Order flow reveals institutional intent before price moves. Aggressive absorption and delta divergence signal high-probability short-term directional moves.",
      idealRegime: "any_liquid",
      winRate: 71,
      avgRR: 0.8,
      avgHoldTime: "5-30 minutes",
      riskPerTrade: "0.5% of paper capital",
      entryRules: [
        "CVD divergence from price (price flat, delta surging in one direction)",
        "Order book imbalance > 3:1 at key level (bid/ask ratio)",
        "Large resting orders being absorbed (iceberg detection)",
        "Footprint chart shows aggressive buying/selling at key price level",
        "Spread tightening after recent widening (market maker confidence returning)",
      ],
      exitRules: [
        "Fixed target: 0.5% from entry",
        "Stop: 0.3% from entry",
        "Exit on CVD reversal",
        "Time stop: 15 minutes maximum hold",
      ],
      invalidationRules: [
        "Spread widens significantly (liquidity withdrawal)",
        "Large market order executes against position direction",
        "News event occurs during hold period",
      ],
      strengths: ["Very high win rate", "Quick trades reduce exposure", "Works in any regime with liquidity", "Low capital at risk per trade"],
      weaknesses: ["Requires institutional-grade data feeds", "High execution cost from frequent trading", "Slippage kills edge on less liquid pairs", "Mentally exhausting"],
      version: "1.0.0",
      isActive: false,
      powersDecisions: false,
      ruleSource: "server/services/trading/strategies.ts",
      lastUsedAt: null,
    },
  ];
}
