import { queueNexoraTask } from "./nexoraAutonomyFoundation";

const workerTemplates = [
  {
    worker: "office_lead_hunter",
    area: "office",
    actions: [
      "scan_new_fitout_opportunities",
      "qualify_inbound_leads",
      "request_floorplans"
    ]
  },
  {
    worker: "quote_builder",
    area: "office",
    actions: [
      "prepare_budget_quote",
      "build_workspace_estimate",
      "prepare_followup"
    ]
  },
  {
    worker: "supplier_negotiator",
    area: "office",
    actions: [
      "request_supplier_pricing",
      "compare_supplier_margin",
      "prepare_procurement_sheet"
    ]
  },
  {
    worker: "trading_signal_worker",
    area: "trading",
    actions: [
      "scan_prediction_market_edges",
      "run_probability_review",
      "prepare_paper_trade"
    ]
  },
  {
    worker: "learning_worker",
    area: "learning",
    actions: [
      "score_old_results",
      "promote_good_patterns",
      "demote_bad_patterns"
    ]
  },
  {
    worker: "safety_guard_worker",
    area: "safety",
    actions: [
      "check_risk_limits",
      "audit_worker_health",
      "monitor_runtime"
    ]
  }
];

const generatedWorkers: any[] = [];

function now() {
  return new Date().toISOString();
}

export function buildNexoraWorkerArmy(input: any = {}) {
  const created: any[] = [];

  for (const template of workerTemplates) {
    const worker = {
      id: `worker_${Date.now()}_${Math.random().toString(36).slice(2)}`,
      worker: template.worker,
      area: template.area,
      actions: template.actions,
      status: "active",
      autonomy: "safe",
      createdAt: now(),
    };

    generatedWorkers.push(worker);
    created.push(worker);

    for (const action of template.actions) {
      queueNexoraTask({
        worker: template.worker,
        area: template.area,
        action,
        risk: template.area === "trading" ? "medium" : "safe",
        payload: {
          autoGenerated: true,
          source: "worker_factory",
        },
      });
    }
  }

  return {
    ok: true,
    service: "nexora_worker_factory",
    nexoraBrain: true,
    workersCreated: created.length,
    taskBurstsCreated: created.reduce((n, x) => n + x.actions.length, 0),
    workers: created,
    createdAt: now(),
  };
}

export function getNexoraWorkerArmy() {
  return {
    ok: true,
    service: "nexora_worker_factory",
    totalWorkers: generatedWorkers.length,
    workers: generatedWorkers,
    updatedAt: now(),
  };
}
